apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quaicu-kernel.fullname" . }}-config
  labels:
    {{- include "quaicu-kernel.labels" . | nindent 4 }}
data:
  kernel.toml: |
    {{- .Values.kernelConfig | nindent 4 }}
