{{- if .Values.app.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "alis.fullname" . }}-app
  namespace: {{ include "alis.namespace" . }}
  labels:
    {{- include "alis.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  minAvailable: {{ .Values.app.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "alis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
